command: ["python", "-m", "streamlit", "run", "app.py",
          "--server.enableWebsocketCompression=false",
]
         

env:
  - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
    value: "false"
  - name: "AGENT_ENDPOINT_NAME"
    value: "REPLACE_WITH_ENDPOINT_NAME"
  - name: "ENV"
    value: "dev"
  - name: GENIE_SPACE_1
    valueFrom: vod_kpi_agent
  - name: GENIE_SPACE_2
    valueFrom: viewership_agent
